env:
  node: true
  jest: true
plugins:
  - babel
  - jest
extends: 
  - 'eslint:recommended'
  - 'airbnb-base'
  - 'plugin:jest/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "babel-eslint"
rules:
  no-console: 0
  